# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 602bdb71c95b73c637ce4d597c56345f522a179c18fc500aad63557d137b71d15e3059dd729cbf361223ebae55a0d3557e009cb364929c7b0ad43174e662dc75

test:
  secret_key_base: e4bbb4dec9988663f97922bb230c29697517dbc9820630fb89ca3704c21ee098399814d764d30d29e7540072139d50ecc1c18d512504119a4a918718f200678d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
